# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-04 16:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awward', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Profile',
            new_name='profile',
        ),
    ]
