# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-07 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awward', '0002_auto_20190104_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='content',
            field=models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=1),
        ),
    ]
